### ISSUE TITLE
memset() fails for negative byte value

### ISSUE THREAD

**Issue by geoffstreeter** [bavison/arm-mem#1]
memset()  does not honour the "converted to an unsigned char" required by 7.21.6.1 of ISO/IEC 9899:1999(E)

signed char smallint = -3;
signed char smallarray[10];

memset(smallarray, smallint, 10);

results in smallarray[0] ←→ -3
           smallarray[1] ←→ -1
           smallarray[2] ←→ -1
           smallarray[3] ←→ -1
           smallarray[4] ←→ -3
...
code widens the smallint of -3 to int with sign extension - correctly. memset() fails to AND this with 0xff before shifting and ORing.

**Comment by bavison** [comment]
Thanks for reporting this! Sorry I didn't spot your report earlier, I'm not in the habit of checking for issues for this repo and there's no automatic notification from github, as far as I know.

I've just committed a new revision with this issue fixed, 4fc4e7c

**Comment by geoffstreeter** [comment]
On Monday 09 Mar 2015 06:32:01 bavison wrote:

> Thanks for reporting this! Sorry I didn't spot your report earlier, I'm not
> in the habit of checking for issues for this repo and there's no automatic
> notification from github, as far as I know.
> 
> I've just committed a new revision with this issue fixed, 4fc4e7c
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/bavison/arm-mem/issues/1#issuecomment-77853151

Brilliant. Thanks.
