### ISSUE TITLE
v8 aarch64 version

### ISSUE THREAD

**Issue by frankie-zeng** [bavison/arm-mem#10]
Do you have plan to add armmem for aarch64 platform?

**Comment by bavison** [comment]
I wouldn't rule it out, but no immediate plans. I generally add to the library when I discover specific bottlenecks in the glibc implementations in particular applications that I'm working on, and I haven't encountered any yet for AArch64.

It's worth noting that the ARM11 doesn't support AArch64, so only the Cortex-A53 implementations would be worth a direct port. However, even Cortex-A53 is getting a bit long in the tooth nowadays, so often "use a faster core" is an easier solution!

**Comment by frankie-zeng** [comment]
thanks.
