### ISSUE TITLE
memcpy slower than libc on Allwinner A20

### ISSUE THREAD

**Issue by pritambaral** [bavison/arm-mem#2]
Benchmarked using `CacheBench` from [LLCbench](http://icl.cs.utk.edu/projects/llcbench/index.htm).
#### Steps to reproduce:
- Download and extract llcbench
- Compile llcbench's `cachebench`:

```
cd </path/to/extracted/llcbench/directory>
make linux-lam
make cache-bench
```
- Run cachebench's memcpy benchmarks:

```
./cachebench/cachebench -p
```
- Compare results with and without libarmmem.so

**Comment by bavison** [comment]
This library was really only ever targeted at the Raspberry Pi, and as you have found, what is an optimal routine for one particular ARM core design is often not so for other designs. The original Raspberry Pi used an ARM1176JZF-S core, but as it happens, I'm in the process of extending the library to cater for the Raspberry Pi 2, which by lucky coincidence for you, uses the same CPU as the Allwinner A20, namely the Cortex-A7. You may wish to try again with one of the latest revisions of the library.

**Comment by pritambaral** [comment]
I no longer have access to an Allwinner A20. You may close this issue if you want.
