### ISSUE TITLE
valgrind trouble / deprecated SETEND instructions

### ISSUE THREAD

**Issue by rsaxvc** [bavison/arm-mem#6]
Valgrind crashes during memcmp() due to the presence (really lack of implementation in Valgrind) of SETEND. ARM has deprecated these instructions, though they're still available in A32 and T32.

This pull request: https://github.com/bavison/arm-mem/pull/5 Removes the SETEND instructions and replaces them with REV instructions, which I expect to be a few cycles slower, but work with valgrind.

**Comment by bavison** [comment]
PR merged, thanks
