### ISSUE TITLE
Compatibility with Raspbian Buster?

### ISSUE THREAD

**Issue by MichaIng** [bavison/arm-mem#8]
Hi there,

I just tested to run my RPi (2 Model B) on Raspbian Buster. The current `archive.raspberrypi.org` does not yet contain a Buster repo, just Stretch, however it works fine, besides the package for this git repo: `raspi-copies-and-fills`. I needed to purge it, to allow Raspbian Buster upgrade.

The question is, if this is an issue from source, or if I could compile it also for Raspbian Buster. Maybe there is already a Buster ready compiled package available somewhere 😃?

Ref: https://raspberrypi.stackexchange.com/questions/72594/failed-to-start-udev-kernel-device-manager?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

Thanks for your nice work!
MichaIng

**Comment by tubededentifrice** [comment]
Repro is easy: change `/etc/apt/sources.list` to the `testing` release, run an `apt update && apt dist-upgrade` and watch all systemd failing. DO NOT REBOOT before running `apt purge raspi-copies-and-fills` !

**Comment by asavah** [comment]
This certainly  neither is systemd nor arm-mem bug.
It's debian/raspbian/toolchain(incompatibility between gcc or glibc ABI) bug.
I'm running systemd git master and arm-mem on my custom homegrown OS without a single glitch.

**Comment by XECDesign** [comment]
I've just hit this issue myself. While looking into it, I found that 'test' gives better results without arm-mem on buster anyway.

Any idea whether similar optimisations have found their way upstream?

**Comment by MichaIng** [comment]
For reference: https://bugs.launchpad.net/raspbian/+bug/1779563
I will test the build it myself as well.

€: + https://bugs.launchpad.net/raspbian/+bug/1792818
If someone has an Ubuntu One account, would be helpful to connect those. I am not sure if/how Raspbian devs currently test Raspbian Buster on RPi's without archive.raspberrypi.org providing a Buster repo, but generally it would be great pushing things, solving essential issues like that and by that making life of external testers more easy.
